### ISSUE TITLE
Validation addition: Ensure links have proper references

### ISSUE THREAD

**Issue by nuzzles** [simbleau/convo#10]
Example:
```yaml
root: valid
nodes:
  valid:
    dialogue: "This is a totally valid node"
  valid_with_bad_link:
    dialogue: "This is a totally valid node"
    links:
      - valid: "This is a valid link"
      - invalid_link: "This is an invalid link because `invalid_link` does not exist"
```
